export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAIL = "GET_CUSTOMER_FAIL";

export const GET_DISTRIBUTOR_REQUEST = "GET_DISTRIBUTOR_REQUEST";
export const GET_DISTRIBUTOR_SUCCESS = "GET_DISTRIBUTOR_SUCCESS";
export const GET_DISTRIBUTOR_FAIL = "GET_DISTRIBUTOR_FAIL";

export const GET_DISTRIBUTORS_REQUEST = "GET_DISTRIBUTORS_REQUEST";
export const GET_DISTRIBUTORS_SUCCESS = "GET_DISTRIBUTORS_SUCCESS";
export const GET_DISTRIBUTORS_FAIL = "GET_DISTRIBUTORS_FAIL";

export const RETRIVE_CUSTOMER = "RETRIVE_CUSTOMER";

export const SORT_DISTRIBUTORS = "SORT_DISTRIBUTORS";

export const RESTORE_TOKEN = "RESTORE_TOKEN";
export const LOGOUT = "LOGOUT";

export const GET_CUSTOMER_INVENTORY_REQUEST = "GET_CUSTOMER_INVENTORY_REQUEST";
export const GET_CUSTOMER_INVENTORY_SUCCESS = "GET_CUSTOMER_INVENTORY_SUCCESS";
export const GET_CUSTOMER_INVENTORY_FAIL = "GET_CUSTOMER_INVENTORY_FAIL";
