export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAIL = "GET_CUSTOMER_FAIL";

export const GET_DISTRIBUTOR_REQUEST = "GET_DISTRIBUTOR_REQUEST";
export const GET_DISTRIBUTOR_SUCCESS = "GET_DISTRIBUTOR_SUCCESS";
export const GET_DISTRIBUTOR_FAIL = "GET_DISTRIBUTOR_FAIL";

export const GET_SELLERS_REQUEST = "GET_SELLERS_REQUEST";
export const GET_SELLERS_SUCCESS = "GET_SELLERS_SUCCESS";
export const GET_SELLERS_FAIL = "GET_SELLERS_FAIL";

export const GET_BULKBREAKERS_REQUEST = "GET_BULKBREAKERS_REQUEST";
export const GET_BULKBREAKERS_SUCCESS = "GET_BULKBREAKERS_SUCCESS";
export const GET_BULKBREAKERS_FAIL = "GET_BULKBREAKERS_FAIL";

export const RETRIVE_CUSTOMER = "RETRIVE_CUSTOMER";

export const SORT_SELLERS = "SORT_SELLERS";

export const RESTORE_TOKEN = "RESTORE_TOKEN";
export const LOGOUT = "LOGOUT";

export const GET_CUSTOMER_INVENTORY_REQUEST = "GET_CUSTOMER_INVENTORY_REQUEST";
export const GET_CUSTOMER_INVENTORY_SUCCESS = "GET_CUSTOMER_INVENTORY_SUCCESS";
export const GET_CUSTOMER_INVENTORY_FAIL = "GET_CUSTOMER_INVENTORY_FAIL";

export const UPDATE_PRODUCT_STATUS = "UPDATE_PRODUCT_STATUS";
export const DELETE_INVENTORY_PRODUCT_SUCCESS =
  "DELETE_INVENTORY_PRODUCT_SUCCESS";
export const DELETE_INVENTORY_PRODUCT_FAIL = "DELETE_INVENTORY_PRODUCT_FAIL";
export const DELETE_INVENTORY_PRODUCT_REQUEST =
  "DELETE_INVENTORY_PRODUCT_REQUEST";

export const SELLERS_NOT_NEAR = "SELLERS_NOT_NEAR";
