export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";

export const GET_MYORDERS_REQUEST = "GET_MYORDERS_REQUEST";
export const GET_MYORDERS_SUCCESS = "GET_MYORDERS_SUCCESS";
export const GET_MYORDERS_FAIL = "GET_MYORDERS_FAIL";

export const GET_SINGLE_ORDER_REQUEST = "GET_SINGLE_ORDER_REQUEST";
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS";
export const GET_SINGLE_ORDER_FAIL = "GET_SINGLE_ORDER_FAIL";

export const TOGGLE_ORDER_PLACED = "TOGGLE_ORDER_PLACED";

export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";

export const GET_RECEIVED_ORDERS_REQUEST = "GET_RECEIVED_ORDERS_REQUEST";
export const GET_RECEIVED_ORDERS_SUCCESS = "GET_RECEIVED_ORDERS_SUCCESS ";
export const GET_RECEIVED_ORDERS_FAIL = "GET_RECEIVED_ORDERS_FAIL";

export const FETCH_SINGLE_ORDER_REQUEST = "FETCH_SINGLE_ORDER_REQUEST";
export const FETCH_SINGLE_ORDER_SUCCESS = "FETCH_SINGLE_ORDER_SUCCESS";
export const FETCH_SINGLE_ORDER_FAIL = "FETCH_SINGLE_ORDER_FAIL";
