export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";

export const DECREASE_PRODUCT = "DECREASE_PRODUCT";
export const INCREASE_PRODUCT = "INCREASE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const DELETE_PRODUCT_ORDERING = "DELETE_PRODUCT_ORDERING";

export const INCREASE_PRODUCT_BY_TYPING = "INCREASE_PRODUCT_BY_TYPING";

export const GET_ALLPRODUCTS_SUCCESS = "GET_ALLPRODUCTS_SUCCESS";

export const GET_ALL_COMPANY_PRODUCTS_REQUEST =
  "GET_ALL_COMPANY_PRODUCTS_REQUEST";
export const GET_ALL_COMPANY_PRODUCTS_SUCCESS =
  "GET_ALL_COMPANY_PRODUCTS_SUCCESS";
export const GET_ALL_COMPANY_PRODUCTS_FAIL = "GET_ALL_COMPANY_PRODUCTS_FAIL";
export const UNSAVED_CHANGES = "UNSAVED_CHANGES";
export const ADD_PRODUCT_TOSELL = "ADD_PRODUCT_TOSELL";
export const DELETE_PRODUCT_TO_SELL = "DELETE_PRODUCT_TO_SELL";
export const SAVE_PRODUCTS_REQUEST = "SAVE_PRODUCTS_REQUEST";
export const SAVE_PRODUCTS_SUCCESS = "SAVE_PRODUCTS_SUCCESS";
export const SAVE_PRODUCTS_FAIL = "SAVE_PRODUCTS_FAIL";
