export const Routes = {
  PRODUCTS_SCREEN: "ProductsScreen",
  DISTRIBUTORS_SCREEN: "DistributorsScreen",
  ORDER_DETAILS_SCREEN: "OrderDetails",
  LOCATION_SCREEN: "LocationScreen",
  HOME_SCREEN: "HomeScreen",
  SEARCH_SCREEN: "SearchScreen",
  RATING_SCREEN: "RatingScreen",
  LOGIN_SCREEN: "LoginScreen",
  SIGNUP_SCREEN: "SignupScreen",
  CONTINUE_SCREEN: "ContinueScreen",
  SELECT_CUSTOMER_SCREEN: "SelectCustomer",
  ORDERS_SCREEN: "OrdersScreen",
  SINGLE_DISTRIBUTOR: "SingleDistributor",
  PLACED_ORDERS: "PlacedOrders",
  RECEIVED_ORDERS: "ReceivedOrders",
  PLACED_ORDER_DETAILS: "PlacedOrderDetails",
  RECEIVED_ORDER_DETAILS: "ReceivedOrderDetails",
  ORDERS_SCREEN_BULKBREAKERS: "OrdersBulkbreakers",
  ORDERS_SCREEN_POCS: "OrdersPocs",
};
